### ISSUE TITLE
Navbar Moves from page to page

### ISSUE THREAD

**Issue by galfar-coder** [zlataovce/plshelp#11]
**Describe the bug**
Navbar is moving from page to page

**To Reproduce**
Go on main page and then go to log upload, navbar moved a little

**Expected behavior**
Staying in the same place all the time

**Screenshots**
Navbar at main page
![image](https://user-images.githubusercontent.com/60539808/116206126-c7649200-a73e-11eb-85e8-2d0598f36f0a.png)

Navbar at Log Upload and almost everywhere else
![image](https://user-images.githubusercontent.com/60539808/116206242-e19e7000-a73e-11eb-995d-0d8ee78599d7.png)

**Additional context**
Please fix, it triggers me

**Comment by zlataovce** [comment]
control your trigger level  
fixed in latest commit

**Comment by zlataovce** [comment]
instances updated
